name: Artifacts React App
permissions:
  contents: write
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: code
        uses: actions/checkout@v3
      - name: Install Node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install
        uses: npm install
      - name: test
        uses: npm run test >test.txt
        -name: Upload test
        uses: actions/upload-artifact@v3
        with:
          name: testing
          path: test.txt
  download-test:
    name: Download Test
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: DownloadTest
        uses: ations/download-artifact@v3
        with:
          name: testing
      - name: Print result
        shell: bash
        run: |
          value=`cat test.text`
          echo value



