name: Artifacts React App
permissions:
  contents: write
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Run tests and save output
        run: npm run test > test.txt
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test.txt

  download-test:
    name: Download Test Results
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Download Test Artifact
        uses: actions/download-artifact@v3
        with:
          name: test-results
      - name: Print Test Results
        shell: bash
        run: |
          value=$(cat test.txt)
          echo "Test Results: $value"
